/*
    GENERATED BY CLAUDE
*/
#include "CardView.h"
#include "Theme.h"
#include <FL/Fl_Window.H>

namespace {
struct SuitInfo { const char* symbol; Fl_Color color; };

// Card::toString() names its suits "Hearts"/"Diamonds"/"Clubs"/"Spades".
SuitInfo suitInfoFor(const std::string& suitName) {
    if (suitName == "Hearts")   return {"\xE2\x99\xA5", Theme::RedSuit};   // U+2665
    if (suitName == "Diamonds") return {"\xE2\x99\xA6", Theme::RedSuit};   // U+2666
    if (suitName == "Clubs")    return {"\xE2\x99\xA3", Theme::BlackSuit}; // U+2663
    return {"\xE2\x99\xA0", Theme::BlackSuit};                            // U+2660 (Spades)
}
} // namespace

CardView::CardView(int x, int y, int w, int h, int index)
    : Fl_Group(x, y, w, h), index_(index) {
    int cardH = h - 100;

    cardBox_ = new CardFace(x, y, w, cardH);
    cardBox_->color(Theme::CardFace);

    holdButton_ = new Fl_Button(x, y + cardH + 10, w, 40, "Hold");
    holdButton_->type(FL_TOGGLE_BUTTON);
    holdButton_->box(FL_ROUND_UP_BOX);
    holdButton_->color(Theme::DealGreen);
    holdButton_->selection_color(Theme::HeldHighlight);
    holdButton_->labelcolor(Theme::Cream);
    holdButton_->labelfont(FL_HELVETICA_BOLD);
    holdButton_->callback(holdCallback, this);

    discardButton_ = new Fl_Button(x, y + cardH + 60, w, 40, "Discard");
    discardButton_->box(FL_ROUND_UP_BOX);
    discardButton_->color(Theme::DiscardRed);
    discardButton_->labelcolor(Theme::Cream);
    discardButton_->labelfont(FL_HELVETICA_BOLD);
    discardButton_->callback(discardCallback, this);

    end();
}

void CardView::setCardText(const std::string& text) {
    auto sep = text.find(" of ");
    if (sep == std::string::npos) {
        cardBox_->clear();
        return;
    }

    std::string rank = text.substr(0, sep);
    std::string suitName = text.substr(sep + 4);
    SuitInfo info = suitInfoFor(suitName);
    cardBox_->setCard(rank, info.symbol, info.color);
}

void CardView::setHeld(bool held) {
    held_ = held;
    holdButton_->value(held_ ? 1 : 0);
    cardBox_->color(held_ ? Theme::HeldHighlight : Theme::CardFace);
    if (window()) window()->redraw();
    else redraw();
}

void CardView::setOnHoldChanged(std::function<void(int, bool)> cb) {
    onHoldChanged_ = std::move(cb);
}

void CardView::setOnDiscard(std::function<void(int)> cb) {
    onDiscard_ = std::move(cb);
}

void CardView::handleHoldClicked() {
    setHeld(holdButton_->value() != 0);
    if (onHoldChanged_) onHoldChanged_(index_, held_);
}

void CardView::handleDiscardClicked() {
    setCardText("");
    setHeld(false);
    if (onDiscard_) onDiscard_(index_);
}

void CardView::holdCallback(Fl_Widget*, void* data) {
    static_cast<CardView*>(data)->handleHoldClicked();
}

void CardView::discardCallback(Fl_Widget*, void* data) {
    static_cast<CardView*>(data)->handleDiscardClicked();
}
