/*
    GENERATED BY CLAUDE
*/
#include "CoinSlot.h"
#include "Theme.h"

CoinSlot::CoinSlot(int x, int y, int w, int h)
    : Fl_Group(x, y, w, h) {
    int labelH = 25;
    int slotH = h - labelH - 5;

    slotButton_ = new Fl_Button(x + w / 2 - 12, y, 24, slotH, "");
    slotButton_->box(FL_DOWN_BOX);
    slotButton_->color(Theme::SlotMetal);
    slotButton_->selection_color(Theme::Gold);
    slotButton_->callback(slotCallback, this);

    label_ = new Fl_Box(x, y + slotH + 5, w, labelH, "Insert Coins");
    label_->labelfont(FL_HELVETICA_BOLD);
    label_->labelcolor(Theme::Gold);

    end();
}

void CoinSlot::setOnInsertCoin(std::function<void()> cb) {
    onInsertCoin_ = std::move(cb);
}

void CoinSlot::handleSlotClicked() {
    if (onInsertCoin_) onInsertCoin_();
}

void CoinSlot::slotCallback(Fl_Widget*, void* data) {
    static_cast<CoinSlot*>(data)->handleSlotClicked();
}
