/*
    GENERATED BY CLAUDE
*/
#include "PayoutBanner.h"
#include "Theme.h"

PayoutBanner::PayoutBanner(int x, int y, int w, int h)
    : Fl_Group(x, y, w, h) {
    background_ = new Fl_Box(x, y, w, h);
    background_->box(FL_ROUNDED_BOX);
    background_->color(Theme::PanelDark);

    int thirdW = w / 3;

    handNameLabel_ = new Fl_Box(x + 20, y, thirdW, h, "Hand Name");
    handNameLabel_->align(FL_ALIGN_INSIDE | FL_ALIGN_LEFT);
    handNameLabel_->labelfont(FL_HELVETICA_BOLD);
    handNameLabel_->labelsize(18);
    handNameLabel_->labelcolor(Theme::Gold);

    betLabel_ = new Fl_Box(x + thirdW, y, thirdW, h, "Bet: 0");
    betLabel_->align(FL_ALIGN_INSIDE | FL_ALIGN_CENTER);
    betLabel_->labelfont(FL_HELVETICA_BOLD);
    betLabel_->labelsize(16);
    betLabel_->labelcolor(Theme::Cream);

    payoutLabel_ = new Fl_Box(x + 2 * thirdW, y, thirdW - 20, h, "Payout: 0");
    payoutLabel_->align(FL_ALIGN_INSIDE | FL_ALIGN_RIGHT);
    payoutLabel_->labelfont(FL_HELVETICA_BOLD);
    payoutLabel_->labelsize(16);
    payoutLabel_->labelcolor(Theme::Cream);

    end();
}

void PayoutBanner::setHandName(const std::string& name) {
    handNameLabel_->copy_label(name.c_str());
}

void PayoutBanner::setBet(int bet) {
    betLabel_->copy_label(("Bet: " + std::to_string(bet)).c_str());
}

void PayoutBanner::setPayout(int payout) {
    payoutLabel_->copy_label(("Payout: " + std::to_string(payout)).c_str());
}
